# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openl1s.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ropenl1s.proto\x12\x07openl1s\x1a google/protobuf/descriptor.proto\x1a\x1bgoogle/protobuf/empty.proto\"&\n\x06\x43onfig\x12\x1c\n\x05links\x18\x01 \x03(\x0b\x32\r.openl1s.Link\"\xb7\x01\n\x04Link\x12\x10\n\x03src\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x03\x64st\x18\x02 \x01(\tH\x01\x88\x01\x01\x12*\n\x04mode\x18\x03 \x01(\x0e\x32\x17.openl1s.Link.Mode.EnumH\x02\x88\x01\x01\x1a\x46\n\x04Mode\">\n\x04\x45num\x12\x0f\n\x0bunspecified\x10\x00\x12\x12\n\x0eunidirectional\x10\x01\x12\x11\n\rbidirectional\x10\x02\x42\x06\n\x04_srcB\x06\n\x04_dstB\x07\n\x05_mode\"\xa8\x01\n\x05\x45rror\x12\x11\n\x04\x63ode\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12+\n\x04kind\x18\x02 \x01(\x0e\x32\x18.openl1s.Error.Kind.EnumH\x01\x88\x01\x01\x12\x0e\n\x06\x65rrors\x18\x03 \x03(\t\x1a=\n\x04Kind\"5\n\x04\x45num\x12\x0f\n\x0bunspecified\x10\x00\x12\x0e\n\nvalidation\x10\x01\x12\x0c\n\x08internal\x10\x02\x42\x07\n\x05_codeB\x07\n\x05_kind\"\x1b\n\x07Warning\x12\x10\n\x08warnings\x18\x01 \x03(\t\"\x91\x01\n\x07Version\x12\x1d\n\x10\x61pi_spec_version\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0bsdk_version\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0b\x61pp_version\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\x13\n\x11_api_spec_versionB\x0e\n\x0c_sdk_versionB\x0e\n\x0c_app_version\",\n\x07Success\x12!\n\x07warning\x18\x01 \x01(\x0b\x32\x10.openl1s.Warning\"(\n\x07\x46\x61ilure\x12\x1d\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x0e.openl1s.Error\"3\n\x10SetConfigRequest\x12\x1f\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x0f.openl1s.Config\"#\n\x11SetConfigResponse\x12\x0e\n\x06string\x18\x01 \x01(\t\"7\n\x12GetVersionResponse\x12!\n\x07version\x18\x01 \x01(\x0b\x32\x10.openl1s.Version2\x90\x01\n\x07Openapi\x12\x42\n\tSetConfig\x12\x19.openl1s.SetConfigRequest\x1a\x1a.openl1s.SetConfigResponse\x12\x41\n\nGetVersion\x12\x16.google.protobuf.Empty\x1a\x1b.openl1s.GetVersionResponseB\x13Z\x11./openl1s;openl1sb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openl1s_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\021./openl1s;openl1s'
  _CONFIG._serialized_start=89
  _CONFIG._serialized_end=127
  _LINK._serialized_start=130
  _LINK._serialized_end=313
  _LINK_MODE._serialized_start=218
  _LINK_MODE._serialized_end=288
  _LINK_MODE_ENUM._serialized_start=226
  _LINK_MODE_ENUM._serialized_end=288
  _ERROR._serialized_start=316
  _ERROR._serialized_end=484
  _ERROR_KIND._serialized_start=405
  _ERROR_KIND._serialized_end=466
  _ERROR_KIND_ENUM._serialized_start=413
  _ERROR_KIND_ENUM._serialized_end=466
  _WARNING._serialized_start=486
  _WARNING._serialized_end=513
  _VERSION._serialized_start=516
  _VERSION._serialized_end=661
  _SUCCESS._serialized_start=663
  _SUCCESS._serialized_end=707
  _FAILURE._serialized_start=709
  _FAILURE._serialized_end=749
  _SETCONFIGREQUEST._serialized_start=751
  _SETCONFIGREQUEST._serialized_end=802
  _SETCONFIGRESPONSE._serialized_start=804
  _SETCONFIGRESPONSE._serialized_end=839
  _GETVERSIONRESPONSE._serialized_start=841
  _GETVERSIONRESPONSE._serialized_end=896
  _OPENAPI._serialized_start=899
  _OPENAPI._serialized_end=1043
# @@protoc_insertion_point(module_scope)
